language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "roryclaasen-github"

jobs:
  include:
    - if: type != pull_request
      after_success:
        - mvn sonar:sonar
        - bash <(curl -s https://codecov.io/bash)
    - if: type = pull_request
      after_success:
        - bash <(curl -s https://codecov.io/bash)

install:
  - mvn '-Dproject.build.id=${TRAVIS_BUILD_NUMBER}' install -DskipTests=true -Dmaven.javadoc.skip=true -V

script:
  - mvn '-Dproject.build.id=${TRAVIS_BUILD_NUMBER}' verify

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
