version: '{build}'

environment:
  SONAR_TOKEN:
    secure: yarBTMzS9XZFPKsrJ3PFYhpcuqPcJeETXvl5JVnxRCKBS7K4X/Ut88dIdNXw4ZP6
  SONAR_PROJECT_KEY: sonar-vcsparser-plugin
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_ORGANIZATION: roryclaasen-github
  GH_PKG_TOKEN:
    secure: Y3RyAQnNrUkgyrJshbzfV1jlIjV0B45IfxGERk/25Jr7q5+tjIoXuNfiguVB7LXo
  GH_PKG_USRER: roryclaasen

cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.sonar\cache'

before_build:
  - ps: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

build_script:
  - ps: mvn "-Dproject.build.id=.$env:APPVEYOR_BUILD_NUMBER" clean install "-DskipTests=true" "-Dmaven.javadoc.skip=true" -V

test_script:
  - ps: mvn "-Dproject.build.id=.$env:APPVEYOR_BUILD_NUMBER" verify -e

after_test:
  - ps: |
        if (-Not $env:APPVEYOR_PULL_REQUEST_TITLE) {
          mvn "-Dproject.build.id=.$env:APPVEYOR_BUILD_NUMBER" sonar:sonar "-Dsonar.projectKey=$env:SONAR_PROJECT_KEY" "-Dsonar.host.url=$env:SONAR_HOST_URL" "-Dsonar.organization=$env:SONAR_ORGANIZATION" "-Dsonar.branch.name=$env:APPVEYOR_REPO_BRANCH"
        }

on_finish:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml' |
        Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }
  - ps: |
        $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh

artifacts:
  - path: 'target\*.jar'
    name: plugin

before_deploy:
  - ps: |
        if ($env:APPVEYOR_REPO_TAG) {
          mvn --settings settings.xml deploy "-DskipTests=true"
        }

deploy:
  - provider: GitHub
    auth_token:
      secure: G0czgyQ/fEhnzY4D7yQ/6ZBq3ViTBFVJTOfc6wZ+w7vISamtIQmnPb1YxQcA819B
    artifact: plugin
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
