name: Build & Test

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 11.x
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache local Sonar files
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-
    - name: Remove snapshot
      run: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
    - name: Build with Maven
      run: mvn -B package --file pom.xml "-Dproject.build.id=.${{ github.run_number }}"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sonar-vcsparser-plugin
        path: target/sonar-vcsparser-plugin*.jar
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: target/site/jacoco/jacoco.xml
        flags: unittests
    - name: Sonar Scanner
      env:
        SONAR_PROJECT_KEY: sonar-vcsparser-plugin
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_ORGANIZATION: roryclaasen-github
      run: mvn "-Dproject.build.id=.${{ github.run_number }}" sonar:sonar "-Dsonar.host.url=${{ env.SONAR_HOST_URL }}" "-Dsonar.login=${{ secrets.SONAR_TOKEN }}" "-Dsonar.organization=${{ env.SONAR_ORGANIZATION }}" "-Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}" "-Dsonar.branch.name=${{ github.ref }}"
